-- Use a WITH statement to standardize all spellings of Rafa.
-- Then, show the revenue generated by his fanbase for vintage items.

-- Makes sure to replace the NULLs in the product_id column in order_items_vintage with ‘P012’. 
-- Replace the NULLs in the product_id column in order_items with ‘P003’ if you’re joining on that table!

WITH customers_cleaned AS 
( 
  
  SELECT fav_tennis_player, customer_id,
  CASE WHEN fav_tennis_player LIKE 'Rafa%' THEN 'Rafa'
  ELSE fav_tennis_player
  END AS rafa_or_not
  FROM customers
  
),

vintage_table_cleaned AS 

(
  SELECT user_id, sale_price,
  CASE WHEN product_id IS NULL THEN 'P012'
  ELSE product_id
  END AS product_id_clean
  FROM order_items_vintage
  
)

SELECT SUM(vc.sale_price) as revenue
FROM customers_cleaned
JOIN vintage_table_cleaned vc
ON customers_cleaned.customer_id=vc.user_id
WHERE customers_cleaned.rafa_or_not LIKE 'Rafa%'

;









